<?php
#--------------------------------------------------------------------------------------------------
	function getCodeCourses()
	{
		$data['code_courses'] = array(
		array(
			'path' => 'marketing-principles-and-practice',
			'label' => 'The Open University',
			'level' => 'Undergraduate',
			'cardType' => 'ProgramCard',
			'key' => 'marketing-principles-and-practice',
			'imageAlt' => 'Business Management: Marketing Principles and Practice',
			'title' => 'Business Management: Marketing Principles and Practice',
			'introduction' => 'Develop your marketing skills and knowledge to help you make better business decisions and achieve your professional goals.',
			'numberOfweeks' => '10 weeks',
			'courseCount' => '1 course',
			'primariCallToAction' => 'Find out more',
			'url' => 'marketing-principles-and-practice',
			),
		array(
			'path' => 'change-management',
			'label' => 'The Open University',
			'level' => 'Undergraduate',
			'cardType' => 'ProgramCard',
			'key' => 'change-management',
			'imageAlt' => 'Change Management',
			'title' => 'Change Management',
			'introduction' => 'Get professional, accredited training in change management strategy and advance your career towards senior managerial roles.',
			'numberOfweeks' => '10 weeks',
			'courseCount' => '1 course',
			'primariCallToAction' => 'Find out more',
			'url' => 'change-management',
			),
		array('path' => 'change-management',
			'label' => 'The University of Glasgow',
			'level' => 'Postgraduate',
			'cardType' => 'ProgramCard',
			'key' => 'cloud-computing-aws',
			'imageAlt' => 'Cloud Computing Practitioner with AWS Academy Cloud Foundations',
			'title' => 'Cloud Computing Practitioner with AWS Academy Cloud Foundations',
			'introduction' => 'Build the technical skills you need to work in the fast-growing sector of cloud computing and prepare for an AWS Certification.',
			'numberOfweeks' => '12 weeks',
			'courseCount' => '2 courses',
			'primariCallToAction' => 'Find out more',
			'url' => 'cloud-computing-aws',
			),
		array('path' => 'cloud-computing-aws',
			'label' => 'FutureLearn in collaboration with AWS',
			'level' => 'Postgraduate',
			'cardType' => 'ProgramCard',
			'key' => 'critical-international-migration-law',
			'imageAlt' => 'Critical International Migration Law',
			'title' => 'Critical International Migration Law',
			'introduction' => 'Examine the history, context and ever-evolving development of migration control exercised by sovereign states all around the world',
			'numberOfweeks' => '12 weeks',
			'courseCount' => '3 courses',
			'primariCallToAction' => 'Find out more',
			'url' => 'critical-international-migration-law',
			),
		array('path' => 'critical-international-migration-law',
			'label' => 'The University of Kent',
			'level' => 'Postgraduate',
			'cardType' => 'ProgramCard',
			'key' => 'customer-experience-success-salesforce',
			'imageAlt' => 'Customer Experience Management with Salesforce Training',
			'title' => 'Customer Experience Management with Salesforce Training',
			'introduction' => 'Attract, retain and engage customers. Drive commercial value using CX design, analytics and the latest in CRM technology. ',
			'numberOfweeks' => '12 weeks',
			'courseCount' => '2 courses',
			'primariCallToAction' => 'Find out more',
			'url' => 'customer-experience-success-salesforce',
			),
		array('path' => 'customer-experience-success-salesforce',
			'label' => 'FutureLearn in collaboration with Salesforce',
			'level' => 'Postgraduate',
			'cardType' => 'ProgramCard',
			'key' => 'cybersecurity-operations',
			'imageAlt' => 'Cyber Security Operations (Cisco)',
			'title' => 'Cyber Security Operations (Cisco)',
			'introduction' => 'Upskill in cyber security operations and enhance your working knowledge of cyber security with Cisco and The Open University. ',
			'numberOfweeks' => '12 weeks',
			'courseCount' => '1 course',
			'primariCallToAction' => 'Find out more',
			'url' => 'cybersecurity-operations',
			),
		array('path' => 'cybersecurity-operations',
			'label' => 'The Open University endorsed by Cisco Networking Academy',
			'level' => 'Postgraduate',
			'cardType' => 'ProgramCard',
			'key' => 'business-data-analytics-tableau',
			'imageAlt' => 'Data Analytics for Business with Tableau Training',
			'title' => 'Data Analytics for Business with Tableau Training',
			'introduction' => 'Get professional quantitative data analytics training and fast track your career in a leading industry with high job growth.\r\n',
			'numberOfweeks' => '12 weeks',
			'courseCount' => '2 courses',
			'primariCallToAction' => 'Find out more',
			'url' => 'business-data-analytics-tableau',
			),
		array('path' => 'business-data-analytics-tableau',
			'label' => 'FutureLearn in collaboration with Tableau',
			'level' => 'Postgraduate',
			'cardType' => 'ProgramCard',
			'key' => 'data-analytics-for-decision-making',
			'imageAlt' => 'Data Analytics for Decision Making',
			'title' => 'Data Analytics for Decision Making',
			'introduction' => 'Discover the fundamentals of data analytics, and start your journey to becoming a top data scientist.',
			'numberOfweeks' => '12 weeks',
			'courseCount' => '3 courses',
			'primariCallToAction' => 'Find out more',
			'url' => 'data-analytics-for-decision-making',
			),
		array('path' => 'data-analytics-for-decision-making',
			'label' => 'Queen Mary University of London co-created by Institute of Coding',
			'level' => 'Postgraduate',
			'cardType' => 'ProgramCard',
			'key' => 'data-driven-decision-making',
			'imageAlt' => 'Data Science: Data-Driven Decision Making',
			'title' => 'Data Science: Data-Driven Decision Making',
			'introduction' => 'Discover storytelling with data and make better business decisions using data wrangling, modelling, and visualisations in R.',
			'numberOfweeks' => '12 weeks',
			'courseCount' => '3 courses',
			'primariCallToAction' => 'Find out more',
			'url' => 'data-driven-decision-making',
			),
		array('path' => 'data-driven-decision-making',
			'label' => 'Monash University',
			'level' => 'Postgraduate',
			'cardType' => 'ProgramCard',
			'key' => 'digital-photography',
			'imageAlt' => 'Digital Photography: Creating a Professional Portfolio',
			'title' => 'Digital Photography: Creating a Professional Portfolio',
			'introduction' => 'Navigate the fast-moving technological developments in digital photography and build a professional portfolio you’re proud of. ',
			'numberOfweeks' => '10 weeks',
			'courseCount' => '1 course',
			'primariCallToAction' => 'Find out more',
			'url' => 'digital-photography',
			),
		array('path' => 'digital-photography',
			'label' => 'The Open University in collaboration with Royal Photographic Society',
			'level' => 'Undergraduate',
			'cardType' => 'ProgramCard',
			'key' => 'fashion-business',
			'imageAlt' => 'Fashion Business',
			'title' => 'Fashion Business',
			'introduction' => 'Upskill in fashion management for work in fashion marketing, branding, product development, sustainability and entrepreneurship.',
			'numberOfweeks' => '11 weeks',
			'courseCount' => '4 courses',
			'primariCallToAction' => 'Find out more',
			'url' => 'fashion-business',
			),
		array('path' => 'fashion-business',
			'label' => 'Institut Français de la Mode (IFM)',
			'level' => 'Undergraduate',
			'cardType' => 'ProgramCard',
			'key' => 'financial-analysis-xero-tableau',
			'imageAlt' => 'Financial Analysis and Decision Making with Xero and Tableau',
			'title' => 'Financial Analysis and Decision Making with Xero and Tableau',
			'introduction' => 'Get professional training in financial analysis and learn how to translate financial data insights into deliverable actions.',
			'numberOfweeks' => '12 weeks',
			'courseCount' => '2 courses',
			'primariCallToAction' => 'Find out more',
			'url' => 'financial-analysis-xero-tableau',
			),
		array('path' => 'financial-analysis-xero-tableau',
			'label' => 'FutureLearn in collaboration with Xero &amp; Tableau',
			'level' => 'Postgraduate',
			'cardType' => 'ProgramCard',
			'key' => 'fintech-financial-innovation',
			'imageAlt' => 'FinTech - Financial Innovation',
			'title' => 'FinTech - Financial Innovation',
			'introduction' => 'Investigate the changes brought about by FinTech innovation and harness evolving opportunities in the future of FinTech.',
			'numberOfweeks' => '10 weeks',
			'courseCount' => '4 courses',
			'primariCallToAction' => 'Find out more',
			'url' => 'fintech-financial-innovation',
			),
		array('path' => 'fintech-financial-innovation',
			'label' => 'Dublin City University co-created by DCU Business School',
			'level' => 'Postgraduate',
			'cardType' => 'ProgramCard',
			'key' => 'digital-health-in-hospitals',
			'imageAlt' => 'Fundamentals of Digital Health in Hospitals',
			'title' => 'Fundamentals of Digital Health in Hospitals',
			'introduction' => 'Develop your capabilities in digital health implementation and hospital administration.\r\n',
			'numberOfweeks' => '10 weeks',
			'courseCount' => '5 courses',
			'primariCallToAction' => 'Find out more',
			'url' => 'digital-health-in-hospitals',
			),
		array('path' => 'digital-health-in-hospitals',
			'label' => 'Deakin University',
			'level' => 'Postgraduate',
			'cardType' => 'ProgramCard',
			'key' => 'global-development-in-practice',
			'imageAlt' => 'Global Development in Practice: Designing an Intervention',
			'title' => 'Global Development in Practice: Designing an Intervention',
			'introduction' => 'Use development management tools and frameworks to plan, implement and evaluate development interventions in practice. ',
			'numberOfweeks' => '12 weeks',
			'courseCount' => '1 course',
			'primariCallToAction' => 'Find out more',
			'url' => 'global-development-in-practice',
			),
		array('path' => 'global-development-in-practice',
			'label' => 'The Open University',
			'level' => 'Postgraduate',
			'cardType' => 'ProgramCard',
			'key' => 'impact-of-trauma-on-mental-health',
			'imageAlt' => 'Impact of Trauma on Mental Health',
			'title' => 'Impact of Trauma on Mental Health',
			'introduction' => 'Get expert insights into the effects of trauma and establish an understanding of psychological wellbeing and its promotion.',
			'numberOfweeks' => '10 weeks',
			'courseCount' => '1 course',
			'primariCallToAction' => 'Find out more',
			'url' => 'impact-of-trauma-on-mental-health',
			),
		array('path' => 'impact-of-trauma-on-mental-health',
			'label' => 'The University of Glasgow',
			'level' => 'Postgraduate',
			'cardType' => 'ProgramCard',
			'key' => 'international-marketing',
			'imageAlt' => 'International Marketing: Intercultural Communication Management',
			'title' => 'International Marketing: Intercultural Communication Management',
			'introduction' => 'Learn how to manage the international marketing for global brands and services and navigate cultural sensitivity in business.',
			'numberOfweeks' => '10 weeks',
			'courseCount' => '5 courses',
			'primariCallToAction' => 'Find out more',
			'url' => 'international-marketing',
			),
		array('path' => 'international-marketing',
			'label' => 'Anglia Ruskin University endorsed by Institute of Data &amp; Marketing',
			'level' => 'Undergraduate',
			'cardType' => 'ProgramCard',
			'key' => 'politics-turbulent-times',
			'imageAlt' => 'International Relations: Politics in Turbulent Times',
			'title' => 'International Relations: Politics in Turbulent Times',
			'introduction' => 'Explore key political challenges confronting diplomacy in the 21st century and enhance your knowledge of modern global politics.',
			'numberOfweeks' => '12 weeks',
			'courseCount' => '3 courses',
			'primariCallToAction' => 'Find out more',
			'url' => 'politics-turbulent-times',
			),
		array('path' => 'politics-turbulent-times',
			'label' => 'The University of Kent',
			'level' => 'Postgraduate',
			'cardType' => 'ProgramCard',
			'key' => 'management-and-leadership-in-health',
			'imageAlt' => 'Introduction to Management and Leadership in Health Services',
			'title' => 'Introduction to Management and Leadership in Health Services',
			'introduction' => 'Develop your understanding of management and leadership theory to meet the demands of a career in health services management.',
			'numberOfweeks' => '10 weeks',
			'courseCount' => '2 courses',
			'primariCallToAction' => 'Find out more',
			'url' => 'management-and-leadership-in-health',
			),
		array('path' => 'management-and-leadership-in-health',
			'label' => 'The University of Glasgow',
			'level' => 'Postgraduate',
			'cardType' => 'ProgramCard',
			'key' => 'itil-4',
			'imageAlt' => 'ITIL® 4 Foundation Certificate with Official Manual and Exam',
			'title' => 'ITIL® 4 Foundation Certificate with Official Manual and Exam',
			'introduction' => 'Get first-level training in the ITIL® framework, learning the latest version of ITIL to further your IT service management career.',
			'numberOfweeks' => '5 weeks',
			'courseCount' => '1 course',
			'primariCallToAction' => 'Find out more',
			'url' => 'itil-4',
			),
		array('path' => 'itil-4',
			'label' => 'QA  accredited by AXELOS',
			'level' => 'Tengah Cari Daa',
			'cardType' => 'ProgramCard',
			'key' => 'learn-french-for-global-communication-level-1',
			'imageAlt' => 'Learn Beginner French for Global Communication: Language Level 1',
			'title' => 'Learn Beginner French for Global Communication: Language Level 1',
			'introduction' => 'Learn the basics of the French language and build your confidence in speaking French for work and travel.',
			'numberOfweeks' => '10 weeks',
			'courseCount' => '1 course',
			'primariCallToAction' => 'Find out more',
			'url' => 'learn-french-for-global-communication-level-1',
			),
		array('path' => 'learn-french-for-global-communication-level-1',
			'label' => 'King`s College London',
			'level' => 'Postgraduate',
			'cardType' => 'ProgramCard',
			'key' => 'learn-spanish-for-global-communication-level-1',
			'imageAlt' => 'Learn Beginner Spanish for Global Communication: Language Level 1',
			'title' => 'Learn Beginner Spanish for Global Communication: Language Level 1',
			'introduction' => 'Learn the basics of Spanish language and culture and build confidence in your ability to speak Spanish for business and pleasure.',
			'numberOfweeks' => '10 weeks',
			'courseCount' => '1 course',
			'primariCallToAction' => 'Find out more',
			'url' => 'learn-spanish-for-global-communication-level-1',
			),
		array('path' => 'learn-spanish-for-global-communication-level-1',
			'label' => 'King`s College London',
			'level' => 'Postgraduate',
			'cardType' => 'ProgramCard',
			'key' => 'management-of-uncertainty-leadership-decisions-and-action',
			'imageAlt' => 'Management of Uncertainty: Leadership, Decisions and Action  ',
			'title' => 'Management of Uncertainty: Leadership, Decisions and Action  ',
			'introduction' => 'Develop greater leadership skills and learn to make effective decisions in conditions of radical uncertainty.',
			'numberOfweeks' => '12 weeks',
			'courseCount' => '1 course',
			'primariCallToAction' => 'Find out more',
			'url' => 'management-of-uncertainty-leadership-decisions-and-action',
			),
		array('path' => 'management-of-uncertainty-leadership-decisions-and-action',
			'label' => 'The Open University',
			'level' => 'Postgraduate',
			'cardType' => 'ProgramCard',
			'key' => 'online-teaching-accessibility-and-inclusive-learning',
			'imageAlt' => 'Online Teaching: Accessibility and Inclusive Learning',
			'title' => 'Online Teaching: Accessibility and Inclusive Learning',
			'introduction' => 'Make your online teaching accessible and learn how to plan, design, and deliver inclusive learning and teaching online.',
			'numberOfweeks' => '12 weeks',
			'courseCount' => '1 course',
			'primariCallToAction' => 'Find out more',
			'url' => 'online-teaching-accessibility-and-inclusive-learning',
			),
		array('path' => 'online-teaching-accessibility-and-inclusive-learning',
			'label' => 'The Open University',
			'level' => 'Postgraduate',
			'cardType' => 'ProgramCard',
			'key' => 'online-teaching',
			'imageAlt' => 'Online Teaching: Creating Courses for Adult Learners',
			'title' => 'Online Teaching: Creating Courses for Adult Learners',
			'introduction' => 'Learn the practical skills you need to create online courses successfully, and develop your ability to teach adults online.',
			'numberOfweeks' => '12 weeks',
			'courseCount' => '1 course',
			'primariCallToAction' => 'Find out more',
			'url' => 'online-teaching',
			),
		array('path' => 'online-teaching',
			'label' => 'The Open University endorsed by the Association for Learning Technology (ALT)',
			'level' => 'Postgraduate',
			'cardType' => 'ProgramCard',
			'key' => 'online-teaching-improving-and-evaluating-courses',
			'imageAlt' => 'Online Teaching: Evaluating and Improving Courses',
			'title' => 'Online Teaching: Evaluating and Improving Courses',
			'introduction' => 'Develop the skills you need to evaluate the success of your online teaching and enhance your students’ remote learning experience.',
			'numberOfweeks' => '12 weeks',
			'courseCount' => '1 course',
			'primariCallToAction' => 'Find out more',
			'url' => 'online-teaching-improving-and-evaluating-courses',
			),
		array('path' => 'online-teaching-improving-and-evaluating-courses',
			'label' => 'The Open University',
			'level' => 'Postgraduate',
			'cardType' => 'ProgramCard',
			'key' => 'practical-project-management',
			'imageAlt' => 'Practical Project Management',
			'title' => 'Practical Project Management',
			'introduction' => 'Get a professional, accredited introduction to project management from a top UK university.',
			'numberOfweeks' => '10 weeks',
			'courseCount' => '1 course',
			'primariCallToAction' => 'Find out more',
			'url' => 'practical-project-management',
			),
		array('path' => 'practical-project-management',
			'label' => 'The University of Glasgow',
			'level' => 'Postgraduate',
			'cardType' => 'ProgramCard',
			'key' => 'prince2',
			'imageAlt' => 'PRINCE2® 6th Edition: Foundation Certification with Official Manual and Exam',
			'title' => 'PRINCE2® 6th Edition: Foundation Certification with Official Manual and Exam',
			'introduction' => 'Earn a PRINCE2® certification with the UK’s leading project management training provider to advance your career.',
			'numberOfweeks' => '6 weeks',
			'courseCount' => '1 course',
			'primariCallToAction' => 'Find out more',
			'url' => 'prince2',
			),
		array('path' => 'prince2',
			'label' => 'QA  accredited by AXELOS',
			'level' => 'Tengah cari 2.0',
			'cardType' => 'ProgramCard',
			'key' => 'project-management-hr',
			'imageAlt' => 'Project Management: Human Resources and Leadership',
			'title' => 'Project Management: Human Resources and Leadership',
			'introduction' => 'Discover how building strong human resources management skills is key to a successful project management career.',
			'numberOfweeks' => '10 weeks',
			'courseCount' => '5 courses',
			'primariCallToAction' => 'Find out more',
			'url' => 'project-management-hr',
			),
		array('path' => 'project-management-hr',
			'label' => 'Anglia Ruskin University',
			'level' => 'Postgraduate',
			'cardType' => 'ProgramCard',
			'key' => 'research-methods',
			'imageAlt' => 'Research Methods',
			'title' => 'Research Methods',
			'introduction' => 'Learn effective research methods for conducting academic and professional research with Griffith and Deakin University.',
			'numberOfweeks' => '13 weeks',
			'courseCount' => '1 course',
			'primariCallToAction' => 'Find out more',
			'url' => 'research-methods',
			),
		array('path' => 'research-methods',
			'label' => 'Deakin University co-created by Griffith University',
			'level' => 'Postgraduate',
			'cardType' => 'ProgramCard',
			'key' => 'entrepreneurial-sales',
			'imageAlt' => 'Sales Skills for Today: An Introduction to Entrepreneurial Sales',
			'title' => 'Sales Skills for Today: An Introduction to Entrepreneurial Sales',
			'introduction' => 'Learn how to sell in today’s complex marketplace and gain in-demand sales skills to accelerate your career progression.',
			'numberOfweeks' => '12 weeks',
			'courseCount' => '7 courses',
			'primariCallToAction' => 'Find out more',
			'url' => 'entrepreneurial-sales',
			),
		array('path' => 'entrepreneurial-sales',
			'label' => 'Entrepreneurial Sales Institute (ESI) endorsed by Verizon Connect',
			'level' => 'Undergraduate',
			'cardType' => 'ProgramCard',
			'key' => 'sports-coaching',
			'imageAlt' => 'Sports Coaching',
			'title' => 'Sports Coaching',
			'introduction' => 'Learn how to develop, lead, and motivate high performing sports teams using impactful sports coaching strategies.',
			'numberOfweeks' => '10 weeks',
			'courseCount' => '1 course',
			'primariCallToAction' => 'Find out more',
			'url' => 'sports-coaching',
			),
		array('path' => 'sports-coaching',
			'label' => 'Deakin University',
			'level' => 'Postgraduate',
			'cardType' => 'ProgramCard',
			'key' => 'sustainability-development',
			'imageAlt' => 'Sustainability and Development',
			'title' => 'Sustainability and Development',
			'introduction' => 'Explore sustainability, human development and environmental impact in the context of development programs.',
			'numberOfweeks' => '12 weeks',
			'courseCount' => '5 courses',
			'primariCallToAction' => 'Find out more',
			'url' => 'sustainability-development',
			),
		array('path' => 'sustainability-development',
			'label' => 'Deakin University',
			'level' => 'Postgraduate',
			'cardType' => 'ProgramCard',
			'key' => 'teacher-training-embedding-mental-health-in-the-curriculum',
			'imageAlt' => 'Teacher Development: Embedding Mental Health in the Curriculum',
			'title' => 'Teacher Development: Embedding Mental Health in the Curriculum',
			'introduction' => 'Develop skills to design inclusive teaching, learning and assessment activities that enhance student mental health and wellbeing.',
			'numberOfweeks' => '12 weeks',
			'courseCount' => '1 course',
			'primariCallToAction' => 'Find out more',
			'url' => 'teacher-training-embedding-mental-health-in-the-curriculum',
			),
		array('path' => 'teacher-training-embedding-mental-health-in-the-curriculum',
			'label' => 'The Open University endorsed by Mental Health Foundation',
			'level' => 'Postgraduate',
			'cardType' => 'ProgramCard',
			'key' => 'teaching-healthcare-professionals',
			'imageAlt' => 'Teaching Healthcare Professionals',
			'title' => 'Teaching Healthcare Professionals',
			'introduction' => 'Enhance your teaching practice as a health professional and gain accredited, professional skills in health professions education.',
			'numberOfweeks' => '10 weeks',
			'courseCount' => '4 courses',
			'primariCallToAction' => 'Find out more',
			'url' => 'teaching-healthcare-professionals',
			),
		array('path' => 'teaching-healthcare-professionals',
			'label' => 'The University of Glasgow',
			'level' => 'Postgraduate',
			'cardType' => 'ProgramCard',
			'key' => 'understanding-consumer-behaviour',
			'imageAlt' => 'Understanding Consumer Behaviour: Customer Decision-Making and the Customer Journey',
			'title' => 'Understanding Consumer Behaviour: Customer Decision-Making and the Customer Journey',
			'introduction' => 'Get to know your target consumer’s buying behaviour and learn how to implement effective cross-channel marketing campaigns.',
			'numberOfweeks' => '10 weeks',
			'courseCount' => '5 courses',
			'primariCallToAction' => 'Find out more',
			'url' => 'understanding-consumer-behaviour',
			),
		array(
			'path' => '',
			'label' => 'Anglia Ruskin University endorsed by Institute of Data & Marketing',
			'level' => 'Undergraduate',
			'cardType' => 'ProgramCard',
			'key' => '',
			'imageAlt' => 'International Marketing: Intercultural Communication Management',
			'title' => 'Understanding Consumer Behaviour: Customer Decision-Making and the Customer Journey',
			'introduction' => 'Get to know your target consumer’s buying behaviour and learn how to implement effective cross-channel marketing campaigns.',
			'numberOfweeks' => '10 weeks',
			'courseCount' => '5 courses',
			'primariCallToAction' => 'Find out more',
			'url' => 'understanding-consumer-behaviour',
			),
		);
		#
		return $data;
	}
#--------------------------------------------------------------------------------------------------
